name: Daily Commit Action

on:
  workflow_dispatch:
  schedule:
    - cron: '0 0 * * *'  # every day at midnight UTC

permissions:
  contents: write  # ✅ this is REQUIRED for pushing

jobs:
  daily-commit:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Make a daily commit
        run: |
          date >> daily-log.txt
          git config --global user.name "github-actions[bot]"
          git config --global user.email "21f3000697@ds.study.iitm.ac.in"
          git add .
          git commit -m "Automated daily commit"
          git push
