name: Daily Commit Action

on:
  schedule:
    - cron: '0 0 * * *' # runs daily at midnight UTC
  workflow_dispatch:

permissions:
  contents: write

jobs:
  daily-commit:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Add timestamp to file - 21f3000697@ds.study.iitm.ac.in
        run: |
          echo "Commit on $(date)" >> daily-log.txt

      - name: Commit changes
        run: |
          git config --global user.name "21f3000697"
          git config --global user.email "21f3000697@ds.study.iitm.ac.in"
          git add .
          git commit -m "Automated commit on $(date)" || echo "Nothing to commit"

      - name: Push using PAT
        run: |
          git remote set-url origin https://21f3000697:${{ secrets.MY_PAT }}@github.com/21f3000697/daily-commit-test.git
          git push origin main
